version: '3'

services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb"]

  init-dynamodb:
    build:
      context: .
      dockerfile: Dockerfile.init
    depends_on:
      - dynamodb